api: '1.20.6'
name: Economy 
version: '1.0'
main: com.github.yuqingliu.economy.Main
api-version: '1.13'
softdepend: [ Vault ]
commands:
  deposit:
    description: Deposit currency into user's purse
    usage: /deposit <currencyName> <amount>; /deposit <playerName> <currencyName> <amount>
    permission: economy.admin
  withdraw:
    description: Removes currency from user's purse
    usage: /withdraw <currencyName> <amount>; /withdraw <playerName> <currencyName> <amount>
    permission: economy.admin
  currency:
    description: Add/Remove a currency
    usage: /currency add <currencyName>; /currency remove <name>
    permission: economy.admin
  purse:
    description: Opens purse GUI
    usage: /purse
    permission: economy.user
    permission-message: You do not have permission to use this command
  shop:
    description: Create/Delete a shop. Spawns a villager acting as a trading post for that shop.
    usage: /shop create <shopName>; /shop delete <shopName>
    permission: economy.admin
    permission-message: You do not have permission to use this command
  shopsection:
    description: Create/Delete a shop section. Main hand item is used as icon.
    usage: /shopsection create <shopName> <sectionName>; /shopsection delete <shopName> <sectionName>
    permission: economy.admin
    permission-message: You do not have permission to use this command
  shopitem:
    description: Add/Remove main hand item as an option in a shop section
    usage: /shopitem add <shopName> <sectionName>; /shopitem remove <shopName> <sectionName>
    permission: economy.admin
    permission-message: You do not have permission to use this command
  vendor:
    description: Create/Delete a vendor. Spawns a villager acting as a trading post for that shop.
    usage: /vendor create <vendorName>; /vendor delete <vendorName>
    permission: economy.admin
    permission-message: You do not have permission to use this command
  vendorsection:
    description: Create/Delete a vendor section. Main hand item is used as icon.
    usage: /vendorsection create <vendorName> <sectionName>; /vendorsection delete <vendorName> <sectionName>
    permission: economy.admin
    permission-message: You do not have permission to use this command
  vendoritem:
    description: Add/Remove main hand item as an option in a vendor section
    usage: /vendoritem add,update <vendorName> <sectionName> <currencyName1> <buyPrice1> <sellPrice1> <currencyName2> <buyPrice2> <sellPrice2> ...; /vendoritem remove <vendorName> <sectionName>;
    permission: economy.admin
    permission-message: You do not have permission to use this command

permissions:
  economy.admin:
    description: Allows use of admin commands
    default: op
  economy.user:
    description: Allows use of regular commands
    default: true
